#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from std_msgs.msg import Bool
from assignment2_rt.srv import GetAverages

class CmdMux(Node):
    def __init__(self):
        super().__init__('cmd_mux')
        self.get_logger().warn("----- CMD MUX NODE ACTIVE -----")

        self.safety_lock = False
        self.user_cmd = Twist()
        self.rollback_cmd = Twist()

        self.last_velocities = []  # store last 5 velocities

        self.avg_srv = self.create_service(
            GetAverages,
            'get_averages',
            self.get_averages_callback
        )

        self.create_subscription(Twist, '/user_cmd', self.user_callback, 10)
        self.create_subscription(Twist, '/rollback_cmd', self.rollback_callback, 10)
        self.create_subscription(Bool, '/safety_lock', self.safety_callback, 10)

        self.cmd_pub = self.create_publisher(Twist, '/cmd_vel', 10)
        self.timer = self.create_timer(0.05, self.publish_cmd)

    def user_callback(self, msg):
        self.user_cmd = msg

    def rollback_callback(self, msg):
        self.rollback_cmd = msg

    def safety_callback(self, msg):
        self.safety_lock = msg.data

    # if safety lock is activated for a threshold violation, velocity priority goes to rollback 
    def publish_cmd(self):
        if self.safety_lock:
            final_cmd = self.rollback_cmd
        else:
            final_cmd = self.user_cmd

        # publish final command
        self.cmd_pub.publish(final_cmd)

        # store last 5 velocities
        self.last_velocities.append((final_cmd.linear.x, final_cmd.angular.z))
        if len(self.last_velocities) > 5:
            self.last_velocities.pop(0)

    def get_averages_callback(self, request, response):
        if len(self.last_velocities) == 0:
            response.avg_linear = 0.0
            response.avg_angular = 0.0
            return response

        lin = [v[0] for v in self.last_velocities]
        ang = [v[1] for v in self.last_velocities]

        response.avg_linear = sum(lin) / len(lin)
        response.avg_angular = sum(ang) / len(ang)

        return response

def main(args=None):
    rclpy.init(args=args)
    node = CmdMux()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()