#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from std_msgs.msg import Bool

# This node decides what node has the priority to write inside cmd_vel topic and move the robot
#I had to add it because otherwise there were conflict problems between user commands and safety commands

class CmdMux(Node):
    def __init__(self):
        super().__init__('cmd_mux')
        self.get_logger().warn("----- CMD MUX NODE ACTIVE -----")

        self.safety_lock = False
        self.user_cmd = Twist()
        self.rollback_cmd = Twist()

        self.create_subscription(Twist, '/user_cmd', self.user_callback, 10)
        self.create_subscription(Twist, '/rollback_cmd', self.rollback_callback, 10)
        self.create_subscription(Bool, '/safety_lock', self.safety_callback, 10)

        self.cmd_pub = self.create_publisher(Twist, '/cmd_vel', 10)
        self.timer = self.create_timer(0.05, self.publish_cmd)

    def user_callback(self, msg):
        self.user_cmd = msg

    def rollback_callback(self, msg):
        self.rollback_cmd = msg

    def safety_callback(self, msg):
        self.safety_lock = msg.data

    # if safety lock is activated for a threshold violation, velocity priority goes to rollback 
    def publish_cmd(self):
        if self.safety_lock:
            self.cmd_pub.publish(self.rollback_cmd)
        else:
            self.cmd_pub.publish(self.user_cmd)

def main(args=None):
    rclpy.init(args=args)
    node = CmdMux()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()