#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from sensor_msgs.msg import LaserScan

from assignment2_rt.srv import SetThreshold
from assignment2_rt.msg import ObstacleInfo


class ObstacleMonitor(Node):
    def __init__(self):
        super().__init__('obstacle_monitor')

        # Publisher for obstacle info
        self.obs_pub = self.create_publisher(ObstacleInfo, '/obstacle_info', 10)

        # Publisher to stop the robot for safety
        self.cmd_pub = self.create_publisher(Twist, '/cmd_vel', 10)

        # Subscriber to LaserScan
        self.create_subscription(LaserScan, '/scan', self.laser_callback, 10)

        # Service to change threshold
        self.srv = self.create_service(SetThreshold, 'set_threshold', self.set_threshold_callback)

        # Initial threshold
        self.threshold = 0.5

    def set_threshold_callback(self, request, response):
        self.threshold = request.new_threshold
        self.get_logger().info(f"Threshold updated to {self.threshold}")
        response.success = True
        return response

    def laser_callback(self, scan):
        ranges = scan.ranges
        n = len(ranges)

        # Divide scan into left, front, right
        left = min(ranges[0 : n//3])
        front = min(ranges[n//3 : 2*n//3])
        right = min(ranges[2*n//3 : n])

        # Determine direction of closest obstacle
        min_all = min(left, front, right)

        if min_all == front:
            direction = "front"
        elif min_all == left:
            direction = "left"
        else:
            direction = "right"

        # Publish obstacle info
        info = ObstacleInfo()
        info.min_distance = float(min_all)
        info.threshold = float(self.threshold)
        info.is_obstacle = min_all < self.threshold
        info.direction = direction
        self.obs_pub.publish(info)

        # Safety: ONLY stop when too close
        if min_all < self.threshold:
            stop = Twist()
            self.cmd_pub.publish(stop)


def main(args=None):
    rclpy.init(args=args)
    node = ObstacleMonitor()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()