#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from std_msgs.msg import Bool

# The role of this node is to activate rollback safety procedure 

class RollbackController(Node):
    def __init__(self):
        super().__init__('rollback_controller')
        self.get_logger().warn("----- ROLLBACK CONTROLLER ACTIVE -----")

        self.safety_lock = False
        self.rollback_speed = 0.3
        self.rollback_duration = 1.5
        self.elapsed = 0.0

        self.rollback_pub = self.create_publisher(Twist, '/rollback_cmd', 10)

        self.create_subscription(Bool, '/safety_lock', self.safety_callback, 10)

        self.timer = self.create_timer(0.05, self.timer_callback)

    # Prints a message if Rollback is activated. 
    def safety_callback(self, msg):
        if msg.data and not self.safety_lock:
            self.get_logger().warn("Rollback started")
            self.elapsed = 0.0
        self.safety_lock = msg.data

# Moves back if rollback procedure is active, otherwise publishes zero velocity.
    def timer_callback(self):
        if self.safety_lock:
            if self.elapsed < self.rollback_duration:
                cmd = Twist()
                cmd.linear.x = -self.rollback_speed
                self.rollback_pub.publish(cmd)
                self.elapsed += 0.05
            else:
                self.rollback_pub.publish(Twist())
        else:
            self.rollback_pub.publish(Twist())

def main(args=None):
    rclpy.init(args=args)
    node = RollbackController()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()