#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import LaserScan
from std_msgs.msg import Bool, Float32

# This node detects when obstacles threshold are violated

class SafetyDetector(Node):
    def __init__(self):
        super().__init__('safety_detector')
        self.get_logger().warn("----- SAFETY DETECTOR ACTIVE -----")

        self.threshold = 0.5  # soft threshold

        self.safety_pub = self.create_publisher(Bool, '/safety_lock', 10)
        self.min_pub = self.create_publisher(Float32, '/min_distance', 10)

        self.create_subscription(LaserScan, '/scan', self.laser_callback, 10)

    def laser_callback(self, scan):
        clean = [r for r in scan.ranges if r > 0.01]
        if not clean:
            return

        min_dist = min(clean)
        self.min_pub.publish(Float32(data=min_dist))

        # HARD STOP (needed to prevent obstacle hits)
        if min_dist < 0.10:
            self.safety_pub.publish(Bool(data=True))
            return

        # SOFT STOP (this threshold can be imposed by the user)
        if min_dist < self.threshold:
            self.safety_pub.publish(Bool(data=True))
        else:
            self.safety_pub.publish(Bool(data=False))

def main(args=None):
    rclpy.init(args=args)
    node = SafetyDetector()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()