#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from std_msgs.msg import Bool
from assignment2_rt.srv import SetThreshold
import sys, termios, tty, select

# This node lets the user choose robot motion and threshold for obstacles

class UserController(Node):
    def __init__(self):
        super().__init__('user_controller')
        self.get_logger().warn("----- USER CONTROLLER ACTIVE -----")

        self.cmd_pub = self.create_publisher(Twist, '/user_cmd', 10) 

        self.threshold_client = self.create_client(SetThreshold, 'set_threshold')

        while not self.threshold_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().warn("Waiting for SetThreshold service...")

        self.safety_lock = False
        self.create_subscription(Bool, '/safety_lock', self.safety_callback, 10) 

        self.current_cmd = Twist()
        self.timer = self.create_timer(0.05, self.publish_cmd)

        # Allows the user to move robot by wasd keys
        print("\n--- TELEOP ---") 
        print("w/s/a/d = move")
        print("x = stop")
        print("t = set new threshold")
        print("q = quit\n") 

        self.keyboard_loop()

    # If safety lock is activated by safety detector, teleop has to be disabled
    def safety_callback(self, msg):
        self.safety_lock = msg.data
        if self.safety_lock:
            print("\n[SAFETY] Rollback active: teleop disabled\n")
            self.current_cmd = Twist()


    # Read a single key without blocking or requiring ENTER.
    # Switch terminal to raw mode, check for input for 50 ms,
    # read one character if available, then restore normal settings.
    def get_key(self):
        tty.setraw(sys.stdin.fileno())
        rlist, _, _ = select.select([sys.stdin], [], [], 0.05)
        key = sys.stdin.read(1) if rlist else None
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
        return key

    # User choice actions
    def keyboard_loop(self):
        while rclpy.ok():
            key = self.get_key()
            if key is None:
                rclpy.spin_once(self)
                continue

            if self.safety_lock:
                continue

            cmd = Twist()
            if key == "w":
                cmd.linear.x = 0.4
            elif key == "s":
                cmd.linear.x = -0.4
            elif key == "a":
                cmd.angular.z = 1.0
            elif key == "d":
                cmd.angular.z = -1.0
            elif key == "x":
                cmd = Twist()
            elif key == 't':
                try:
                    new_thr = float(input("Enter new threshold: "))
                    req = SetThreshold.Request()
                    req.threshold = new_thr

                    future = self.threshold_client.call_async(req)

                    def callback(fut):
                        try:
                            resp = fut.result()
                            print(f"Threshold updated to {resp.new_threshold}")
                        except Exception as e:
                            print(f"Service call failed: {e}")

                    future.add_done_callback(callback)

                except ValueError:
                    self.get_logger().error("Invalid threshold value")
            elif key == "q":
                break
            else:
                continue

            self.current_cmd = cmd

    def publish_cmd(self):
        self.cmd_pub.publish(self.current_cmd)

def main(args=None):
    global settings
    settings = termios.tcgetattr(sys.stdin)

    rclpy.init(args=args)
    node = UserController()
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()