#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from std_msgs.msg import Bool
from assignment2_rt.srv import SetThreshold, GetAverages
import sys, termios, tty, select

class UserController(Node):
    def __init__(self):
        super().__init__('user_controller')
        self.get_logger().warn("----- USER CONTROLLER ACTIVE -----")

        self.cmd_pub = self.create_publisher(Twist, '/user_cmd', 10)

        # --- service clients ---
        self.threshold_client = self.create_client(SetThreshold, 'set_threshold')
        self.avg_client = self.create_client(GetAverages, 'get_averages')

        while not self.threshold_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().warn("Waiting for SetThreshold service...")

        while not self.avg_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().warn("Waiting for GetAverages service...")

        # --- safety lock ---
        self.safety_lock = False
        self.create_subscription(Bool, '/safety_lock', self.safety_callback, 10)

        # --- user defined velocities ---
        self.v_lin = 0.4
        self.v_ang = 1.0

        self.current_cmd = Twist()
        self.timer = self.create_timer(0.05, self.publish_cmd)

        # --- user menu ---
        print("\n--- TELEOP ---")
        print("w/s/a/d = move")
        print("x = stop")
        print("t = set new threshold")
        print("v = set linear/angular velocity")
        print("m = get averages")
        print("q = quit\n")

        self.keyboard_loop()

    def safety_callback(self, msg):
        self.safety_lock = msg.data
        if self.safety_lock:
            print("\n[SAFETY] Rollback active: teleop disabled\n")
            self.current_cmd = Twist()

    def get_key(self):
        tty.setraw(sys.stdin.fileno())
        rlist, _, _ = select.select([sys.stdin], [], [], 0.05)
        key = sys.stdin.read(1) if rlist else None
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
        return key

    def keyboard_loop(self):
        while rclpy.ok():
            key = self.get_key()
            if key is None:
                rclpy.spin_once(self)
                continue

            if self.safety_lock:
                continue

            cmd = Twist()

            # --- set motion ---
            if key == "w":
                cmd.linear.x = self.v_lin
            elif key == "s":
                cmd.linear.x = -self.v_lin
            elif key == "a":
                cmd.angular.z = self.v_ang
            elif key == "d":
                cmd.angular.z = -self.v_ang
            elif key == "x":
                cmd = Twist()

            # --- set threshold ---
            elif key == 't':
                try:
                    new_thr = float(input("Enter new threshold: "))
                    req = SetThreshold.Request()
                    req.threshold = new_thr

                    future = self.threshold_client.call_async(req)

                    def callback(fut):
                        try:
                            resp = fut.result()
                            print(f"Threshold updated to {resp.new_threshold}")
                        except Exception as e:
                            print(f"Service call failed: {e}")

                    future.add_done_callback(callback)

                except ValueError:
                    self.get_logger().error("Invalid threshold value")

            # --- set velocities ---
            elif key == 'v':
                try:
                    new_lin = float(input("Enter new linear velocity: "))
                    new_ang = float(input("Enter new angular velocity: "))
                    self.v_lin = new_lin
                    self.v_ang = new_ang
                    print(f"Updated velocities: lin={self.v_lin}, ang={self.v_ang}")
                except ValueError:
                    self.get_logger().error("Invalid velocity value")

            # --- get averages ---
            elif key == 'm':
                req = GetAverages.Request()
                future = self.avg_client.call_async(req)

                def callback(fut):
                    try:
                        resp = fut.result()
                        print(f"\nAverage linear:  {resp.avg_linear:.3f}")
                        print(f"Average angular: {resp.avg_angular:.3f}\n")
                    except Exception as e:
                        print(f"Service call failed: {e}")

                future.add_done_callback(callback)

            elif key == "q":
                break
            else:
                continue

            self.current_cmd = cmd

    def publish_cmd(self):
        self.cmd_pub.publish(self.current_cmd)

def main(args=None):
        global settings
        settings = termios.tcgetattr(sys.stdin)

        rclpy.init(args=args)
        node = UserController()
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
        main()